#include<iostream>
#include<chrono>
#include<thread>
#include<filesystem>
#include<linuxsampler/Sampler.h>
#include<linuxsampler/drivers/audio/AudioOutputDeviceFactory.h>

namespace fs = std::__fs::filesystem;

int main() {
    auto sampler = new LinuxSampler::Sampler();
    auto factory = new LinuxSampler::AudioOutputDeviceFactory();

    auto params = std::map<std::string, std::string>();
    params["BUFFERSIZE"] = "2048";
    params["BUFFERS"] = "4";
    auto device = factory->Create("COREAUDIO", params);
auto flute = sampler->AddSamplerChannel();
flute->SetAudioOutputDevice(device);
flute->SetEngineType("SFZ");
flute->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "001/005_Flute_harmonique.sfz").string().c_str(),
  0);
flute->GetEngineChannel()->LoadInstrument();

auto viola = sampler->AddSamplerChannel();
viola->SetAudioOutputDevice(device);
viola->SetEngineType("SFZ");
viola->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/020_Viola_8_Flute_4.sfz").string().c_str(),
  0);
viola->GetEngineChannel()->LoadInstrument();

auto pedal = sampler->AddSamplerChannel();
pedal->SetAudioOutputDevice(device);
pedal->SetEngineType("SFZ");
pedal->GetEngineChannel()->PrepareLoadInstrument(
(fs::current_path() / ".." / ".." / "resources" / "sfz" / "Jeux14" / "000/112_Prin.(ped.)16+8.sfz").string().c_str(),
  0);
pedal->GetEngineChannel()->LoadInstrument();

 std::this_thread::sleep_for(std::chrono::milliseconds(1000));
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(73, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(73, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(73, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(73, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(75, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(75, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(75, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(75, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(62, 80, 0);
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(62, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(44, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(66, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(44, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
viola->GetEngineChannel()->SendNoteOff(66, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(68, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(68, 80, 0);
viola->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(66, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(70, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(70, 80, 0);
viola->GetEngineChannel()->SendNoteOn(68, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(73, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(44, 80, 0);
viola->GetEngineChannel()->SendNoteOff(68, 80, 0);
viola->GetEngineChannel()->SendNoteOn(66, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(73, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(66, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(44, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(37, 80, 0);
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(37, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(42, 80, 0);
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(42, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(67, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
viola->GetEngineChannel()->SendNoteOff(67, 80, 0);
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(62, 80, 0);
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(62, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(44, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(66, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(44, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
viola->GetEngineChannel()->SendNoteOff(66, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(68, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(68, 80, 0);
viola->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(66, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(70, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(70, 80, 0);
viola->GetEngineChannel()->SendNoteOn(68, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(73, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(47, 80, 0);
viola->GetEngineChannel()->SendNoteOff(68, 80, 0);
viola->GetEngineChannel()->SendNoteOn(66, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(73, 80, 0);
flute->GetEngineChannel()->SendNoteOn(71, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(66, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(47, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(49, 80, 0);
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
flute->GetEngineChannel()->SendNoteOff(71, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(49, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(51, 80, 0);
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(51, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(67, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(75, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(67, 80, 0);
viola->GetEngineChannel()->SendNoteOn(67, 80, 0);
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(75, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(44, 80, 0);
viola->GetEngineChannel()->SendNoteOff(67, 80, 0);
viola->GetEngineChannel()->SendNoteOn(68, 80, 0);
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(60, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(68, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(60, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(44, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(47, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(47, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(51, 80, 0);
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(60, 80, 0);
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(60, 80, 0);
viola->GetEngineChannel()->SendNoteOn(62, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(51, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
viola->GetEngineChannel()->SendNoteOff(62, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(65, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(65, 80, 0);
viola->GetEngineChannel()->SendNoteOn(67, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(75, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(67, 80, 0);
viola->GetEngineChannel()->SendNoteOn(67, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
flute->GetEngineChannel()->SendNoteOff(75, 80, 0);
flute->GetEngineChannel()->SendNoteOn(70, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(42, 80, 0);
viola->GetEngineChannel()->SendNoteOff(67, 80, 0);
viola->GetEngineChannel()->SendNoteOn(68, 80, 0);
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
flute->GetEngineChannel()->SendNoteOff(70, 80, 0);
flute->GetEngineChannel()->SendNoteOn(68, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(42, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(44, 80, 0);
viola->GetEngineChannel()->SendNoteOff(68, 80, 0);
viola->GetEngineChannel()->SendNoteOn(63, 80, 0);
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(59, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
flute->GetEngineChannel()->SendNoteOff(68, 80, 0);
flute->GetEngineChannel()->SendNoteOn(65, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
flute->GetEngineChannel()->SendNoteOff(65, 80, 0);
flute->GetEngineChannel()->SendNoteOn(66, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
pedal->GetEngineChannel()->SendNoteOff(44, 80, 0);
pedal->GetEngineChannel()->SendNoteOn(39, 80, 0);
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
flute->GetEngineChannel()->SendNoteOff(66, 80, 0);
flute->GetEngineChannel()->SendNoteOn(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(54, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(63, 80, 0);
viola->GetEngineChannel()->SendNoteOn(56, 80, 0);
viola->GetEngineChannel()->SendNoteOff(59, 80, 0);
viola->GetEngineChannel()->SendNoteOn(53, 80, 0);
viola->GetEngineChannel()->SendNoteOff(54, 80, 0);
viola->GetEngineChannel()->SendNoteOn(51, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(56, 80, 0);
viola->GetEngineChannel()->SendNoteOn(61, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
viola->GetEngineChannel()->SendNoteOff(61, 80, 0);
viola->GetEngineChannel()->SendNoteOn(58, 80, 0);
viola->GetEngineChannel()->SendNoteOff(53, 80, 0);
viola->GetEngineChannel()->SendNoteOn(55, 80, 0);
flute->GetEngineChannel()->SendNoteOff(63, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
viola->GetEngineChannel()->SendNoteOff(51, 80, 0);
std::this_thread::sleep_for(std::chrono::milliseconds(1000));
pedal->GetEngineChannel()->SendNoteOff(39, 80, 0);
viola->GetEngineChannel()->SendNoteOff(58, 80, 0);
viola->GetEngineChannel()->SendNoteOff(55, 80, 0);
 std::this_thread::sleep_for(std::chrono::milliseconds(1000));
}
